import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiNestjs,
  SiGraphql,
  SiPrisma,
  SiPostgresql,
  SiMongodb,
  SiDocker,
  SiGit,
  SiAmazonec2,
  SiJavascript,
  SiNodedotjs,
  SiTailwindcss,
  SiRedux,
  SiFirebase,
  SiVuedotjs,
  SiNuxtdotjs,
  SiPython,
  SiAmazonaws,
} from "react-icons/si";
import {
  FiGithub,
  FiLinkedin,
  FiTwitter,
  FiYoutube,
  FiMail,
  FiMessageCircle,
  FiGlobe,
  FiExternalLink,
} from "react-icons/fi";
import { IconType } from "react-icons";

const iconMap: Record<string, IconType> = {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiNestjs,
  SiGraphql,
  SiPrisma,
  SiPostgresql,
  SiMongodb,
  SiDocker,
  SiGit,
  SiAmazonec2,
  SiJavascript,
  SiNodedotjs,
  SiTailwindcss,
  SiRedux,
  SiFirebase,
  SiVuedotjs,
  SiNuxtdotjs,
  SiPython,
  SiAmazonaws,
  FiGithub,
  FiLinkedin,
  FiTwitter,
  FiYoutube,
  FiMail,
  FiMessageCircle,
  FiGlobe,
  FiExternalLink,
};

export default iconMap;
